services:

  postgres:
    image: postgres:15
    container_name: auth-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth-service-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://postgres:5432/auth_service_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data: